import type { Metadata } from "next";
import { LegalShell } from "@/components/legal-shell";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms for using ResumAI: a one-time $9.99 purchase grants 30 days of access with no auto-renewal. AI-generated content is provided as-is.",
  alternates: { canonical: "/terms" },
};

const TermsPage = () => {
  return (
    <LegalShell
      title="Terms of Service"
      updated="June 28, 2026"
      intro="By using ResumAI, you agree to these terms. We've tried to keep them short and readable."
    >
      <h2>The service</h2>
      <p>
        ResumAI is an AI-powered tool that rewrites and tailors your resume based
        on the content you provide. You are responsible for the accuracy of the
        information you enter.
      </p>

      <h2>Access and payment</h2>
      <p>
        A one-time payment of <strong>$9.99</strong> grants you 30 days of
        access. This is a single charge — it does <strong>not</strong>{" "}
        auto-renew, and we do not keep your card on file. Access is tracked in
        your browser on the device you paid on; clearing your browser data may
        remove that access.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Access is for your personal use. You agree not to resell, redistribute,
        scrape, or share access, and not to attempt to bypass payment, access
        limits, or rate limits.
      </p>
      <p>
        Downloads are unlimited during your 30-day access period, subject to a
        fair-use limit of <strong>5 downloads per hour</strong> to prevent
        automated abuse. This is a rolling limit — if you reach it, capacity
        frees up again as the hour passes. We may adjust these limits if needed
        to keep the service available and affordable for everyone.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Resume content produced by ResumAI is generated by AI and provided
        &ldquo;as is.&rdquo; We do not guarantee employment, interviews, ATS
        pass-through, or any specific outcome. Always review and edit your resume
        for accuracy before sending it to an employer.
      </p>

      <h2>Intellectual property</h2>
      <p>
        You own the resume content you create. We retain ownership of the
        ResumAI software, templates, and branding.
      </p>

      <h2>Disclaimer and limitation of liability</h2>
      <p>
        ResumAI is provided without warranties of any kind. To the fullest extent
        permitted by law, we are not liable for any indirect or consequential
        damages arising from your use of the service.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms from time to time. Continued use of ResumAI
        after changes means you accept the updated terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms? See our <a href="/contact">contact page</a>.
      </p>
    </LegalShell>
  );
};

export default TermsPage;
